### PR TITLE
Centralized Exception Handling + Clean Framework Observer

### LINKED ISSUE #8: Centralized Exception Handling

### PR DESCRIPTION
**Pull request by sarbagya-acme**

### CODE REVIEW

File: example/lib/features/country/domain/country_entity.dart [hunk 1]
```diff
@@ -8,29 +8,39 @@ class CountryEntity extends Entity {
     this.countries = const [],
     this.continents = const {},
     this.selectedContinentId = 'AS', // AS is country code for Asia.
+    this.errorMessage = '',
```
Comment (ben-acme) [inline example/lib/features/country/domain/country_entity.dart:11]: Is saving an  error message as string an approach we are going to recommend doing? or it is done like this just for the sake of example?

File: lib/src/defaults/providers/firebase/firebase_external_interface.dart [hunk 2]
```diff
@@ -28,15 +26,21 @@ class FirebaseExternalInterface
     on<FirebaseWatchAllRequest>(_withFirebaseWatchAllRequest);
   }
 
+  @override
+  FailureResponse onError(Object error) {
```
Comment (ben-acme) [inline lib/src/defaults/providers/firebase/firebase_external_interface.dart:30]: Downcasting to just objects instead of using Either is a downgrade to using what Functional programming is supposed to fix, I might need to hear more about why you like this more.

File: lib/src/defaults/providers/graphql/src/graphql_external_interface.dart [hunk 3]
```diff
@@ -21,34 +20,46 @@ class GraphQLExternalInterface
...
-          // log the details on the exception here
-          send(Left(FailureResponse()));
-        }
+        final data = await _graphQLService.request(
+          method: GraphQLMethod.query,
+          document: request.document,
+          variables: request.variables,
+        );
+
+        send(GraphQLSuccessResponse(data: data));
```
Comment (ben-acme) [inline lib/src/defaults/providers/graphql/src/graphql_external_interface.dart:29]: Please let's not handle exceptions outside of External interface, that is one of the main design responsibilities for this class. We can discuss this more.

**Review by ben-acme — COMMENTED** [review]
I left a couple of questions that need to be discussed during our meetings.
